server:
  port: 19090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: task-service
          uri: http://host.docker.internal:18081
          predicates:
            - Path=/tasks/**

        - id: project-service
          uri: http://host.docker.internal:9090
          predicates:
            - Path=/projects/**

        - id: employee-service
          uri: http://host.docker.internal:18080
          predicates:
            - Path=/employees/**

        - id: assignment-service
          uri: http://host.docker.internal:18082
          predicates:
            - Path=/assignments/**


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG