server:
  port: 19090

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "esta_es_mi_compleja_clave_secreta"

  cloud:
    gateway:
      routes:
        - id: task-service
          uri: http://ms-tareas:18081
          predicates:
            - Path=/tasks/**, /roles/**, /task-roles/**, /task-status/**

        - id: project-service
          uri: http://ms-proyectos:9090
          predicates:
            - Path=/projects/**, /kpis/**, /project-status/**

        - id: employee-service
          uri: http://ms-empleados:18080
          predicates:
            - Path=/employees/**

        - id: assignment-service
          uri: http://ms-asignaciones:18082
          predicates:
            - Path=/assignments/**

        - id: cliente-service
          uri: http://ms-cliente:9091
          predicates:
            - Path=/clientes/**

        - id: auth-service
          uri: http://ms-auth:9094
          predicates:
            - Path=/auth/**

        - id: bff-service
          uri: http://ms-bff:18086
          predicates:
            - Path=/bff/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Task
        url: /tasks/v3/api-docs
      - name: Project
        url: /projects/v3/api-docs
      - name: Employee
        url: /employees/v3/api-docs
      - name: Assignment
        url: /assignments/v3/api-docs
      - name: Clientes
        url: /clientes/v3/api-docs
      - name: Auth
        url: /auth/v3/api-docs
      - name: BFF
        url: /bff/v3/api-docs
