# Desactiva Liquibase en los tests para que no choque con la BD en memoria
spring.liquibase.enabled=false
# Deja que Hibernate cree las tablas rápido solo para el test
spring.jpa.hibernate.ddl-auto=create-drop