spring.application.name=project-service

server.port=9090
spring.datasource.url=jdbc:mysql://mysql-db:3306/db_project?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

task.service.url=http://ms-empleados:18080