spring.application.name=project-service

server.port=9090
spring.datasource.url=jdbc:mysql://localhost:3306/db_project?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

task.service.url=http://localhost:18081

# Configuración del Consumidor de Kafka
spring.kafka.consumer.bootstrap-servers=kafka-1:29092
spring.kafka.consumer.group-id=proyecto-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-init-sql=SELECT 1

# Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml


# Configuración de Resend
resend.api.key=re_P9294oqZ_6sjZf3XEsesdFqBDBJikeDJc
resend.email.from=onboarding@resend.dev
resend.email.to=bmtqrs@gmail.com

springdoc.api-docs.path=/projects/v3/api-docs

# Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml