spring.application.name=bff

server.port=18086
#task.service.url=http://localhost:18081
#project.service.url=http://localhost:9090
task.service.url=http://ms-tareas:18081
project.service.url=http://ms-proyectos:9090

springdoc.api-docs.path=/bff/v3/api-docs
