spring.application.name=assignment
server.port=18082

spring.datasource.url=jdbc:mysql://innova-db:3306/db_assignments?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración del Productor Kafka
spring.kafka.producer.bootstrap-servers=kafka-1:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# Configuración de URLs
app.urls.employee=http://ms-gateway:19090/employees/rut/
app.urls.task-role=http://ms-gateway:19090/task-roles/

springdoc.api-docs.path=/assignments/v3/api-docs